classes = [
  'toast-container',
  'position-fixed',
  'end-0',
  'bottom-0',
  'mb-2',
  'me-2',
  'toast',
  'toast-header',
  'toast-body',
  'text-bg-primary',
  'text-bg-secondary',
  'text-bg-info',
  'text-bg-warning',
  'text-bg-success',
  'text-bg-dark',
  'text-bg-light',
  'text-bg-danger',
  'bg-primary-subtle',
  'bg-secondary-subtle',
  'bg-info-subtle',
  'bg-warning-subtle',
  'bg-success-subtle',
  'bg-dark-subtle',
  'bg-light-subtle',
  'bg-danger-subtle',
  'btn-close',
]
